### ISSUE TITLE
Where to test?

### ISSUE THREAD

**Issue by dereksilva** [vikaskyadav/bloom-login#1]
Hi, where can I see the app in action? Can you please provide some screenshots, as requested in the bounty?

**Comment by ctrlaltvikas** [comment]
oh sorry, I forgot to attach screenshot. I'm adding screenshots to readme.md

**Comment by ctrlaltvikas** [comment]
@dereksilva . I've updated the readme with screenshot. If you want to run the code. You can just clone and do `npm install` and `npm start`. I hope it will work.:)
